version: "3.9"

services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"
        hostname: my-rabbit
        container_name: some-rabbit
